### ISSUE TITLE
[Bug] Newly caught fish are all being treated as common

### ISSUE THREAD

**Issue by BeSlightly** [konstfish/fISHbot#2]
Currently your /stats is treating every new caught fish as common.

When you catch either rare, epic or legendary it's counted towards common.
(See screenshots)

Please fix konstfraud.

![image](https://github.com/konstfish/fISHbot/assets/80231852/4866e263-a087-44f0-9d13-6f36be844ab9)
![image](https://github.com/konstfish/fISHbot/assets/80231852/0d4a91fb-a891-4c20-81ce-4706497a5b39)

**Comment by konstfish** [comment]
Issue fixed with https://github.com/konstfish/fISHbot/commit/301534089ce213d22414d4afcc9eaf68914db550
